package com.innitsocial.abcdish.common.jobs;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.Map;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class BackgroundJobService {

    private final JdbcTemplate jdbcTemplate;
    private final ObjectMapper objectMapper;

    @PostConstruct
    void repairTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS abcdish.background_jobs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type VARCHAR(100) NOT NULL,
                    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                    payload_json TEXT NOT NULL,
                    dedupe_key VARCHAR(255) NOT NULL,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT,
                    available_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    locked_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP,
                    CONSTRAINT uk_background_jobs_dedupe_key UNIQUE (dedupe_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS idx_background_jobs_claim
                ON abcdish.background_jobs(status, available_at, id)
                """);
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS idx_background_jobs_type_status
                ON abcdish.background_jobs(type, status)
                """);
    }

    public void enqueue(String type, String dedupeKey, Map<String, Object> payload) {
        try {
            jdbcTemplate.update("""
                            INSERT INTO abcdish.background_jobs (type, dedupe_key, payload_json, status)
                            VALUES (?, ?, ?, 'PENDING')
                            ON CONFLICT (dedupe_key) DO UPDATE SET
                                status = CASE
                                    WHEN abcdish.background_jobs.status IN ('FAILED', 'PENDING') THEN 'PENDING'
                                    ELSE abcdish.background_jobs.status
                                END,
                                available_at = CASE
                                    WHEN abcdish.background_jobs.status IN ('FAILED', 'PENDING') THEN CURRENT_TIMESTAMP
                                    ELSE abcdish.background_jobs.available_at
                                END,
                                last_error = CASE
                                    WHEN abcdish.background_jobs.status IN ('FAILED', 'PENDING') THEN NULL
                                    ELSE abcdish.background_jobs.last_error
                                END
                            """,
                    type,
                    dedupeKey,
                    objectMapper.writeValueAsString(payload)
            );
        } catch (JsonProcessingException error) {
            throw new IllegalArgumentException("Unable to serialize background job payload", error);
        }
    }

    public Optional<ClaimedJob> claimNextJob(int maxAttempts) {
        return jdbcTemplate.query("""
                        WITH next_job AS (
                            SELECT id
                            FROM abcdish.background_jobs
                            WHERE status = 'PENDING'
                              AND attempts < ?
                              AND available_at <= CURRENT_TIMESTAMP
                            ORDER BY id
                            LIMIT 1
                            FOR UPDATE SKIP LOCKED
                        )
                        UPDATE abcdish.background_jobs job
                        SET status = 'RUNNING',
                            locked_at = CURRENT_TIMESTAMP,
                            attempts = attempts + 1
                        FROM next_job
                        WHERE job.id = next_job.id
                        RETURNING job.id, job.type, job.payload_json, job.attempts
                        """,
                (rs, rowNum) -> new ClaimedJob(
                        rs.getLong("id"),
                        rs.getString("type"),
                        rs.getString("payload_json"),
                        rs.getInt("attempts")
                ),
                maxAttempts
        ).stream().findFirst();
    }

    public void complete(long jobId) {
        jdbcTemplate.update("""
                        UPDATE abcdish.background_jobs
                        SET status = 'COMPLETED',
                            completed_at = CURRENT_TIMESTAMP,
                            locked_at = NULL,
                            last_error = NULL
                        WHERE id = ?
                        """,
                jobId
        );
    }

    public void fail(long jobId, String message, int attempts, int maxAttempts) {
        String status = attempts >= maxAttempts ? "FAILED" : "PENDING";
        long retryDelaySeconds = Math.min(300, Math.max(10, attempts * 20L));
        jdbcTemplate.update("""
                        UPDATE abcdish.background_jobs
                        SET status = ?,
                            available_at = CURRENT_TIMESTAMP + (? * INTERVAL '1 second'),
                            locked_at = NULL,
                            last_error = ?
                        WHERE id = ?
                        """,
                status,
                retryDelaySeconds,
                abbreviate(message),
                jobId
        );
    }

    private String abbreviate(String value) {
        if (value == null) {
            return "";
        }
        String cleaned = value.trim();
        return cleaned.length() <= 2000 ? cleaned : cleaned.substring(0, 2000);
    }

    public record ClaimedJob(
            long id,
            String type,
            String payloadJson,
            int attempts
    ) {
    }
}
