spring:
  application:
    name: abcdish-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Panda
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_schema: abcdish

  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug